########################################################################
##
## General docs: https://docs.docker.com/compose/compose-file
##
## Note: most images here are based on Alpine Linux, which is a
##       minimal Linux install, perfect for Docker images, but
##       if you ever want to jump on it, use `sh` instead of `bash`
##
########################################################################

version: '2'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: invo
      MYSQL_USER: root
    volumes:
      - ./schemas/invo.sql:/docker-entrypoint-initdb.d/invo.sql

  php:
    image: phalcon:7.0-fpm-alpine
    build: .
    volumes:
      - .:/var/www/html
    links:
      - db

  web:
    image: nginx:stable-alpine
    user: root   # needs to be started by root to get access to ports under 1024, but nginx will be run by "nginx"
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./app/config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
